### ISSUE TITLE
Make user unable to create new token if they generated token already and it didn't expire

### ISSUE THREAD

**Issue by hwangs12** [hwangs12/marketplace_authentication_starter#5]
use the user payload to block generation of new token for already generated one for the user and if it didn't expire, also block the generation of new token

**Comment by hwangs12** [comment]
currently, the token can be generated indefinitely

**Comment by sunyongpark2021** [comment]
Once a token is generated, put it in useState and change that useState into a boolean value using !!. As long as that booleaned useState value  == true, no token can be generated. Once the token expires, booleaned useState value changes to false and a new token can be generated?

**Comment by hwangs12** [comment]
sure, we can do that in the native app like you said but this is for implementation from the express app. What I would do is create a middlewhere that checks decrypted payload from user token, and check for expiry. Another question is how would we know that the user has a generated token? One way is to save the user token in our db or add a user attribute 'logged-in' in our db so we mark it true when user hits sign-in endpoint.

**Comment by hwangs12** [comment]
closing this issue as it is enabled with the following PR
[link](https://github.com/hwangs12/marketplace_authentication_starter/pull/10)
